Repository hafs-community/HAFS, pull requests merged in 2021-11, with the labels that each got.

#105 Enable Online Satbias Capabilities
  parm/analysis/gsi/gsiparm.anl.tmp
  parm/hafs.conf
  parm/hafs_holdvars.conf
  parm/hafs_holdvars.txt
  scripts/exhafs_analysis.sh
  scripts/exhafs_analysis_vr.sh
  scripts/exhafs_enkf.sh
  scripts/exhafs_enkf_hx.sh
Labels: enhancement, Ready for Review, Ready to Merge

#109 Update issue and PR templates as well as README.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: Ready for Review, Ready to Merge

#111 Feature/orionfix dpdt
  parm/forecast/globnest/input.nml.tmp
  parm/forecast/globnest/input_nest02.nml.tmp
  parm/forecast/globnest_hwrf/input.nml.tmp
  parm/forecast/globnest_hwrf/input_nest02.nml.tmp
  parm/forecast/regional/input.nml.tmp
  parm/forecast/regional_hwrf/input.nml.tmp
  rocoto/sites/orion.ent
Labels: Ready for RTs, Ready to Merge
